dist: xenial
language: python
python:
    - "3.6"
    - "3.7"
    - "3.8"
    - "3.9-dev"

env:
    - variant=1
    - variant=2

# command to install dependencies
install:
    - if [ "$variant" = "1" ]; then pip install .; fi
    - if [ "$variant" = "2" ]; then pip install . tqdm; fi

script: pytest

notifications:
    email: false
